### ISSUE TITLE
Error: Alvin0\RedisModel\Builder::__construct(): Argument #1 ($connection) 

### ISSUE THREAD

**Issue by vsmartcode** [alvin0/redis-model#2]
![image](https://user-images.githubusercontent.com/4949809/228429760-be93f300-61ce-4356-bf11-da29bfb3fd4c.png)
i got the same error, what is the solution?

**Comment by alvin0** [comment]
Please install the predis with command:

`composer require predis/predis`

I going to add it to require composer json in next version. Sorry about that!

**Comment by alvin0** [comment]
> ![image](https://user-images.githubusercontent.com/4949809/228429760-be93f300-61ce-4356-bf11-da29bfb3fd4c.png)
> 
> i got the same error, what is the solution?

Please update to version 0.4. Thanks for used my package <3
