### ISSUE TITLE
Chunking Types Mismatch

### ISSUE THREAD

**Issue by kornatzky** [alvin0/redis-model#7]
Here is the code:

```
use Alvin0\RedisModel\Collection;
use App\RedisModels\Bid as RedisBid;
```

where `'auction_id_item_id'` is the primary key of RedisBid.

The following crashes, 

```
RedisBid::where('auction_id_item_id', '14_20')
->chunk(100, function (Collection $bids) {}):
```

where I have at least one match key. 

The error is, 

`TypeError: {closure}(): Argument #1 ($bids) must be of type Alvin0\RedisModel\Collection, array given, called in vendor/alvin0/redis-model/src/Builder.php on line 330`

Which is weird. The usage of the package looks all right. 

So it is possibly a bug. 

Would appreciate if you check this.

**Comment by kornatzky** [comment]
Previously we had a problem with chunking when there were no results. And you fixed it.

**Comment by alvin0** [comment]
Hello there, it seems that this is not a bug.

The callback will receive a list item in the array format, so when you check the instanceof `Collection`, PHP will throw a type error.
Please use the following example instead. Have a great day at work!

```php
RedisBid::where('auction_id_item_id', '14_20')->chunk(100, function ($bids) {
    dd($bids);
});
```

**Comment by kornatzky** [comment]
Yes. I got it. It works. Thanks for the prompt response. Good luck.

**Comment by kornatzky** [comment]
Closing it.
