### ISSUE TITLE
The model casting is not functioning as expected after retrieving the data from the Redis database.

### ISSUE THREAD

**Issue by agrism** [alvin0/redis-model#9]
Hello,

I'm encountering a casting issue when querying a model from the database. I have defined the property cast as 'array', but after retrieving the data from Redis, the output appears as a string instead of an array.

Versions:
Laravel version: 8.83.27
"alvin0/redis-model": "^0.6.2"
PHP Version 8.2.8

```
<?php

namespace App\Models;

use Alvin0\RedisModel\Model;

/**
 * @property string $id
 * @property array $payload
 */
class MyModel extends Model
{
    protected $subKeys = [
    	'id',
    	'payload',
    ];

    protected $fillable = [
    	'id',
    	'payload',
    ];

    protected $casts = [
        'payload' => 'array',
    ];

    protected $primaryKey = 'id';

    public $incrementing = true;

    protected $table = "my_models"
	
}
```

usage:
```
<?php

App\Models\MyModel::query()->destroy();

$model = new App\Models\MyModel;
$model->payload = ['a' => 2];
$model->save();

dump($model->payload);
// The output is array as expected ['a' => 2]

$payload = App\Models\MyModel::first()->payload;


dump($payload);
// The output is a string '{"a":2}' instead of an array
```

**Comment by ed9** [comment]
I have the same problem, the casts do not work when loading model from redis.

**Comment by neblonds** [comment]
Any solutions to this??? Encountered the same issue.

**Comment by alvin0** [comment]
## Notice:
First, I'd like to issue a warning regarding the use of subKeys. `$subKeys` is designed to help you filter data with the fillable attributes you've declared in `$fillable`. I do not recommend using an array with these fillable attributes, as it can potentially lead to errors with the colon character `:`.

## Back to the problem:
I have transformed the data retrieved from Redis during the creation of each model.

- checkout version 0.6.3 -> https://github.com/alvin0/redis-model/releases/tag/0.6.3
- This is commit fix it -> https://github.com/alvin0/redis-model/commit/12b50c33ca8d29b4ccd0c85620846cbfa76abdad

## Thanks  and please consider adding a star to this package to help it reach a wider audience .

**Comment by agrism** [comment]
The latest package update functions flawlessly! I appreciate your hard work and dedication. You've definitely earned a star rating from me.
